service: rank-analyse

package:
  exclude:
  - ./**
  include:
  - ./bin/**

provider:
  name: aws
  runtime: go1.x
  profile: uptactics
  memorySize: 128
  region: us-east-1 # US East 1 (N. Virginia)
  stage: ${opt:stage, 'staging'}
  lambdaHashingVersion: "20201221"
  apiGateway:
    shouldStartNameWithService: true
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    # Allow all SNS
    - Effect: "Allow"
      Resource: "*"
      Action:
        - sns:*

functions:
  # == Authorizers ==
  Authoriser:
    handler: bin/Authoriser
    environment:
      JWT_SECRET: ${self:custom.env.JWT_SECRET}

  # == HTTP ==
  Healthcheck:
    handler: bin/Healthcheck
    events:
      - http:
          path: /healthcheck
          method: get

  RunCrawl:
    handler: bin/RunCrawl
    events:
      - http:
          path: /run-crawl
          method: post
          authorizer:
            name: Authoriser
            resultTtlInSeconds: 0
    environment:
      SNS_PREFIX: ${self:custom.env.SNS_PREFIX}

  LambdaTest:
    handler: bin/LambdaTest
    vpc: ${self:custom.${self:provider.stage}.vpc}
    environment:
      DB_CONN_URL: ${self:custom.env.DB_CONN_URL}
    events:
      - http:
          path: /lambda-test
          method: get
          authorizer:
            name: Authoriser
            resultTtlInSeconds: 0

  GetCrawl:
    handler: bin/GetCrawl
    vpc: ${self:custom.${self:provider.stage}.vpc}
    environment:
      DB_CONN_URL: ${self:custom.env.DB_CONN_URL}
    events:
      - http:
          path: /crawls/{id}
          method: get
          parameters:
            paths:
              id: true
          authorizer:
            name: Authoriser
            resultTtlInSeconds: 0

  # == SNS ==
  ProcessKeyword:
    handler: bin/ProcessKeyword
    events:
      - sns: ${self:service}-${self:provider.stage}-ProcessKeyword
    timeout: 120 # 2 Minutes timeout to fetch data from Zenserp
    vpc: ${self:custom.${self:provider.stage}.vpc}
    environment:
      ZENSERP_API_KEY: ${self:custom.env.ZENSERP_API_KEY}
      SNS_PREFIX: ${self:custom.env.SNS_PREFIX}
      DB_CONN_URL: ${self:custom.env.DB_CONN_URL}

  ResultCreatedExtractPageInfo:
    handler: bin/ResultCreatedExtractPageInfo
    events:
      - sns: ${self:service}-${self:provider.stage}-ResultCreated
    timeout: 120 # 2 Minutes timeout to fetch and extract data
    vpc: ${self:custom.${self:provider.stage}.vpc}
    environment:
      SNS_PREFIX: ${self:custom.env.SNS_PREFIX}
      DB_CONN_URL: ${self:custom.env.DB_CONN_URL}

custom:
  env:
    JWT_SECRET: ${ssm:/${self:service}/${self:provider.stage}/JWT_SECRET~true}
    DB_CONN_URL: ${ssm:/${self:service}/${self:provider.stage}/DB_CONN_URL~true}
    SNS_PREFIX: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${self:service}-${self:provider.stage}'
    ZENSERP_API_KEY: ${ssm:/${self:service}/${self:provider.stage}/ZENSERP_API_KEY~true}

  staging:
    vpc:
      securityGroupIds: ${ssm:/uptactics/${self:provider.stage}/DEFAULT_SECURITY_GROUP}
      subnetIds: ${ssm:/uptactics/${self:provider.stage}/PRIVATE_SUBNET_IDS~split}
  production:
    vpc:
      securityGroupIds: ${ssm:/uptactics/${self:provider.stage}/DEFAULT_SECURITY_GROUP}
      subnetIds: ${ssm:/uptactics/${self:provider.stage}/PRIVATE_SUBNET_IDS~split}
