service: rank-analyse

package:
  exclude:
  - ./**
  include:
  - ./bin/**

provider:
  name: aws
  runtime: go1.x
  profile: uptactics
  memorySize: 128
  region: us-east-1 # US East 1 (N. Virginia)
  stage: ${opt:stage, 'staging'}
  lambdaHashingVersion: "20201221"
  apiGateway:
    shouldStartNameWithService: true
  tracing:
    apiGateway: true
    lambda: true

functions:
  # == HTTP ==
  Healthcheck:
    handler: bin/Healthcheck
    events:
      - http:
          path: /healthcheck
          method: get

  LambdaTest:
    handler: bin/LambdaTest
    vpc: ${self:custom.${self:provider.stage}.vpc}
    events:
      - http:
          path: /lambda-test
          method: get

custom:
  env:
  staging:
    vpc:
      securityGroupIds:
        - sg-0ccb205c68f536ac2
      subnetIds:
        - subnet-0628f9575f9059627
        - subnet-0d5ec2eebacf30940
  production:
    vpc:
      securityGroupIds:
        - sg-05842fc6e1964a2db
      subnetIds:
        - subnet-054fdbbe3e3323b9b
        - subnet-099c3beddd054f8f7
